# Generated by Django 3.2.4 on 2024-09-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(fields=('SeriesName', 'Brand'), name='UX_Series_SeriesName_Brand'),
        ),
    ]
