# Generated by Django 3.2.4 on 2024-09-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_series_ux_series_seriesname_brand'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Quantity', models.PositiveIntegerField()),
                ('Collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collections')),
                ('Series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.series')),
            ],
            options={
                'ordering': ['Name', 'Series'],
            },
        ),
    ]
