# Generated by Django 3.2.4 on 2024-09-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collectionitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='Image',
            field=models.ImageField(default='../default_post_e9srbd', upload_to='images/'),
        ),
    ]
