# Generated by Django 3.2.4 on 2024-09-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_name'),
        ('posts', '0001_initial'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedislike', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LikingProfile', to='profiles.profile'),
        ),
    ]
