# Generated by Django 3.2.4 on 2024-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('FollowingProfile', 'FollowedProfile'), name='UX_Follower_Follower_Followed'),
        ),
    ]
